### ISSUE TITLE
eps should be added to variance

### ISSUE THREAD

**Issue by milani** [taokong/group_normalization#1]
In the following line, eps should be added to variance not to the std, according to the paper. So the correct implementation is `(var + eps).sqrt()`
https://github.com/taokong/group_normalization/blob/28b4d629ca59851a8a1278997aa6c0d1460ef8c6/group_norm.py#L20

**Comment by taokong** [comment]
@milani The eps is just to avoid division by zero problem, so the implementation is equivalent to the paper.
